name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./NotWuphfDocumentation
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Cheezco/NotWuphf
          TARGET_BRANCH: master
          BUILD_SCRIPT: npm run docs:build
          BUILD_DIR: docs/.vuepress/dist
